services:
  47hed3cu5a:
    container_name: 47hed3cu5a_app
    image: ghcr.io/mr-devloper005/hiddengemsreno.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3061:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
